version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netshoes
      MYSQL_USER: netshoes
      MYSQL_PASSWORD: netshoes
    ports:
      - "3306:3306"
